name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Format, Init, Validate, Plan & Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: NATWEST
        run: terraform init

      - name: Terraform Validate
        working-directory: NATWEST
        run: terraform validate

      - name: Terraform Plan
        working-directory: NATWEST
        run: |
          terraform plan \
            -var="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -out=tfplan

      - name: Terraform Apply
        working-directory: NATWEST
        run: |
          terraform apply \
            -var="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -auto-approve tfplan

      - name: Upload Terraform State
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: NATWEST/terraform.tfstate
