name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Format, Init, Validate, Plan
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        working-directory: NATWEST
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: NATWEST
        run: terraform init

      - name: Terraform Validate
        working-directory: NATWEST
        run: terraform validate

      - name: Terraform Plan
        working-directory: NATWEST
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: NATWEST/tfplan

  apply:
    name: Terraform Apply (Manual Trigger)
    runs-on: ubuntu-latest
    needs: terraform
    if: github.event_name == 'workflow_dispatch'

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: NATWEST
        run: terraform init

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: NATWEST

      - name: Terraform Apply
        working-directory: NATWEST
        run: terraform apply -auto-approve tfplan
